-- =============================================================================
-- BISAFIT PLATFORM - COMPREHENSIVE DEPLOYMENT AUDIT FIX MIGRATION
-- Migration ID : bisafit_audit_fix_round_001
-- Generated : 2025-01-01
-- Author : BisaFit Engineering / Senior DB Engineer
-- Environment : Production (Supabase)
-- Deployment : Applied directly via Supabase Management API
-- =============================================================================
--
-- OVERVIEW
-- --------
-- This file documents ALL schema, function, policy, index, trigger, and
-- constraint changes introduced during the BisaFit deployment audit fix
-- round. The SQL statements described below were applied atomically via
-- the Supabase Management API and are recorded here for version control,
-- disaster-recovery, and peer-review purposes.
--
-- STATUS : APPLIED (DO NOT RE-RUN WITHOUT IDEMPOTENCY REVIEW)
--
-- =============================================================================
-- SECTION 1 : TABLES CREATED (26 tables)
-- =============================================================================
--
-- 1.  bisafit_exercise_library
--       Core exercise catalogue: name, category, muscle_groups,
--       equipment_needed, difficulty, demo_url, instructions, metadata.
--
-- 2.  bisafit_coach_clients
--       Maps coach user_id -> client user_id with status, notes,
--       assigned_plan_id, started_at, ended_at.
--
-- 3.  bisafit_messages
--       In-app direct messaging: sender_id, receiver_id, content,
--       read_at, thread_id, attachment_url.
--
-- 4.  bisafit_wearable_connections
--       OAuth tokens for third-party wearables: user_id, provider
--       (garmin|fitbit|apple_health|whoop|polar), access_token (encrypted),
--       refresh_token (encrypted), token_expires_at, scopes, last_synced_at.
--
-- 5.  bisafit_wearable_data
--       Raw + normalised wearable metric rows: connection_id, metric_type,
--       recorded_at, value, unit, raw_payload (jsonb).
--
-- 6.  bisafit_challenges
--       Community or coach-created challenges: title, description,
--       challenge_type, start_date, end_date, goal_value, goal_unit,
--       is_public, created_by, prize_description, banner_url.
--
-- 7.  bisafit_challenge_participants
--       Join table: challenge_id, user_id, joined_at, current_value,
--       completed, completed_at, rank.
--
-- 8.  bisafit_streaks
--       Per-user streak tracking: user_id, streak_type, current_streak,
--       longest_streak, last_activity_date, freeze_tokens_remaining.
--
-- 9.  bisafit_badges
--       Badge catalogue: name, description, icon_url, badge_category,
--       criteria_type, criteria_value, xp_reward.
--
-- 10. bisafit_user_badges
--       User -> Badge award log: user_id, badge_id, awarded_at,
--       notified, source_ref.
--
-- 11. bisafit_xp_log
--       XP event ledger: user_id, event_type, xp_earned, reference_id,
--       reference_table, description, created_at.
--
-- 12. bisafit_subscriptions
--       Active subscription records: user_id, plan_id, stripe_subscription_id,
--       stripe_customer_id, status, current_period_start, current_period_end,
--       cancel_at_period_end, trial_end, grace_period_end, payment_failed_at.
--
-- 13. bisafit_subscription_plans
--       Plan catalogue: name, stripe_price_id, billing_interval,
--       amount_cents, currency, features (jsonb), is_active, display_order.
--
-- 14. bisafit_food_log
--       Nutrition diary: user_id, logged_date, meal_type, food_name,
--       brand, serving_size, serving_unit, calories, protein_g, carbs_g,
--       fat_g, fiber_g, sugar_g, sodium_mg, barcode, source.
--
-- 15. bisafit_water_log
--       Hydration diary: user_id, logged_at, amount_ml, vessel_type.
--
-- 16. bisafit_body_metrics
--       Body composition over time: user_id, measured_at, weight_kg,
--       body_fat_pct, muscle_mass_kg, bmi, waist_cm, hip_cm, chest_cm,
--       notes, source.
--
-- 17. bisafit_daily_summary
--       Denormalised daily rollup (materialised daily by trigger/cron):
--       user_id, summary_date, total_calories_consumed, total_calories_burned,
--       water_ml, workouts_completed, steps, avg_heart_rate, sleep_hours,
--       xp_earned, streak_count.
--
-- 18. bisafit_brand_voice
--       CMS / AI tone settings: key, value, category, description,
--       updated_by (admin only RLS).
--
-- 19. bisafit_roles
--       RBAC role definitions: name, description, permissions (jsonb).
--
-- 20. bisafit_audit_log
--       Immutable audit trail: actor_id, actor_role, action, table_name,
--       record_id, old_data (jsonb), new_data (jsonb), ip_address,
--       user_agent, created_at.
--
-- 21. bisafit_notifications_queue
--       Push / email queue: user_id, notification_type, channel, title,
--       body, data (jsonb), scheduled_at, sent_at, failed_at, retry_count.
--
-- 22. bisafit_integrations
--       Third-party API credentials per user / system: user_id, provider,
--       config (jsonb, encrypted at rest), is_active, last_error.
--
-- 23. bisafit_follows
--       Social follow graph: follower_id, following_id, created_at.
--       Unique constraint on (follower_id, following_id).
--
-- 24. bisafit_workout_likes
--       Likes on workout_log entries: user_id, workout_id, created_at.
--       Unique constraint on (user_id, workout_id).
--
-- 25. bisafit_activity_feed
--       Social timeline events: actor_id, event_type, object_table,
--       object_id, visibility, metadata (jsonb), created_at.
--
-- 26. bisafit_referrals
--       Referral programme ledger: referrer_id, referee_id, code_used,
--       referred_at, reward_granted_at, reward_type, reward_value.
--
-- =============================================================================
-- SECTION 2 : COLUMNS ADDED TO users_profile (26 columns)
-- =============================================================================
--
--  Column name                  Type              Notes
--  ---------------------------  ----------------  ----------------------------
--  role                         text              DEFAULT 'user'
--  fitness_level                text              beginner|intermediate|advanced
--  primary_goal                 text              e.g. weight_loss, muscle_gain
--  secondary_goals              text[]            array of goal slugs
--  available_equipment          text[]            array of equipment slugs
--  workout_days_per_week        integer           1-7
--  preferred_workout_duration   integer           minutes
--  date_of_birth                date              nullable
--  height_cm                    numeric(5,2)      pre-existing column confirmed
--  weight_kg                    numeric(5,2)      pre-existing column confirmed
--  injuries_limitations         text              free text
--  onboarding_completed         boolean           DEFAULT false
--  onboarding_step              integer           DEFAULT 0
--  timezone                     text              IANA tz string
--  preferred_units              text              metric|imperial, DEFAULT metric
--  avatar_url                   text              public CDN URL
--  push_token                   text              FCM / APNs device token
--  push_enabled                 boolean           DEFAULT true
--  email_notifications          boolean           DEFAULT true
--  stripe_customer_id           text              Stripe cus_xxx
--  subscription_status          text              active|trialing|past_due|â¦
--  subscription_plan            text              plan slug
--  subscription_expires_at      timestamptz       nullable
--  referral_code                text              UNIQUE generated code
--  referred_by                  uuid              FK -> users_profile.id
--  customer_id                  text              generic / legacy alias
--
-- =============================================================================
-- SECTION 3 : FUNCTIONS CREATED (21 functions)
-- =============================================================================
--
--  Function                              Returns       Purpose
--  ------------------------------------  ------------  -----------------------
--  exec_sql(sql text)                    void          Admin-only dynamic SQL
--                                                      executor (SECURITY DEFINER)
--
--  bisa_log(...)                         void          Structured audit writer;
--                                                      inserts into bisafit_audit_log
--
--  bisa_notify(...)                      void          Enqueues row into
--                                                      bisafit_notifications_queue
--
--  bisafit_set_updated_at()              trigger       Sets updated_at = NOW()
--                                                      on any UPDATE
--
--  bisa_check_permission(...)            boolean       RBAC helper; checks
--                                                      actor role vs required perm
--
--  bisa_coach_can_access_client(...)     boolean       Returns true if calling
--                                                      user is an active coach
--                                                      for given client_id
--
--  bisa_is_admin()                       boolean       Returns true when
--                                                      auth.uid() has role=admin
--
--  bisafit_update_streak(...)            void          Upserts bisafit_streaks;
--                                                      awards freeze token logic
--
--  bisafit_check_and_award_badges(...)   void          Evaluates badge criteria
--                                                      and inserts user_badges
--                                                      rows; calls bisa_notify
--
--  bisafit_aggregate_daily(...)          void          Rolls up daily stats into
--                                                      bisafit_daily_summary
--                                                      (called by pg_cron)
--
--  bisafit_handle_checkout_completed()   void          Stripe webhook handler:
--                                                      checkout.session.completed
--
--  bisafit_handle_subscription_updated() void          Stripe webhook handler:
--                                                      customer.subscription.updated
--
--  bisafit_handle_subscription_deleted() void          Stripe webhook handler:
--                                                      customer.subscription.deleted
--
--  bisafit_handle_payment_failed()       void          Stripe webhook handler:
--                                                      invoice.payment_failed
--
--  bisafit_enforce_grace_periods()       void          Cron job: downgrades
--                                                      users past grace_period_end
--
--  bisafit_wearable_sync(...)            jsonb         Orchestrates wearable
--                                                      token refresh + data pull;
--                                                      inserts bisafit_wearable_data
--
--  bisafit_complete_onboarding(...)      jsonb         Finalises onboarding,
--                                                      sets onboarding_completed,
--                                                      generates referral_code,
--                                                      awards welcome XP + badge
--
--  bisafit_generate_referral_code(...)   text          Generates unique 8-char
--                                                      alphanumeric referral code
--
--  bisafit_apply_referral_reward(...)    void          Credits referrer XP/plan
--                                                      on first payment of referee
--
--  bisafit_coach_dashboard(...)          jsonb         Returns aggregated view of
--                                                      a coach's client roster,
--                                                      progress, and messages
--
--  bisafit_admin_dashboard()             jsonb         Returns platform-wide KPIs:
--                                                      MAU, revenue, top badges,
--                                                      subscription breakdown
--
-- =============================================================================
-- SECTION 4 : ROW LEVEL SECURITY POLICIES (105 policies)
-- =============================================================================
--
--  Table                              Policy count   Key patterns
--  ---------------------------------  -------------  --------------------------
--  users_profile                           6        self-read/write; admin-all;
--                                                   coach-read-clients
--  bisafit_exercise_library                4        public-read; admin-write
--  bisafit_coach_clients                   5        coach-manage; client-read;
--                                                   admin-all
--  bisafit_messages                        4        sender/receiver-read;
--                                                   sender-insert; admin-all
--  bisafit_wearable_connections            4        owner-only; admin-read
--  bisafit_wearable_data                   3        owner-read; admin-read
--  bisafit_challenges                      5        public-read; creator-manage;
--                                                   admin-all
--  bisafit_challenge_participants          4        self-manage; public-read
--  bisafit_streaks                         3        owner-read; system-write
--  bisafit_badges                          3        public-read; admin-write
--  bisafit_user_badges                     3        owner-read; system-insert;
--                                                   admin-all
--  bisafit_xp_log                          3        owner-read; system-insert
--  bisafit_subscriptions                   4        owner-read; system-write;
--                                                   admin-all
--  bisafit_subscription_plans              3        public-read; admin-write
--  bisafit_food_log                        4        owner-CRUD; coach-read;
--                                                   admin-all
--  bisafit_water_log                       4        owner-CRUD; coach-read
--  bisafit_body_metrics                    4        owner-CRUD; coach-read
--  bisafit_daily_summary                   3        owner-read; coach-read;
--                                                   system-write
--  bisafit_brand_voice                     3        public-read; admin-write
--  bisafit_roles                           2        admin-all; authenticated-read
--  bisafit_audit_log                       2        admin-read; system-insert
--  bisafit_notifications_queue             3        owner-read; system-write;
--                                                   admin-all
--  bisafit_integrations                    3        owner-manage; admin-read
--  bisafit_follows                         5        self-manage; public-read
--  bisafit_workout_likes                   4        self-manage; public-read
--  bisafit_activity_feed                   5        visibility-filtered read;
--                                                   actor-insert; admin-all
--  bisafit_referrals                       4        referrer-read; system-insert;
--                                                   admin-all
--
--  TOTAL                                 105
--
-- =============================================================================
-- SECTION 5 : FOREIGN KEY CONSTRAINTS (38 constraints)
-- =============================================================================
--
--  #   Table                            Column(s)              References
--  --  -------------------------------  ---------------------  -----------------
--  1   bisafit_coach_clients            coach_id               users_profile.id
--  2   bisafit_coach_clients            client_id              users_profile.id
--  3   bisafit_messages                 sender_id              users_profile.id
--  4   bisafit_messages                 receiver_id            users_profile.id
--  5   bisafit_wearable_connections     user_id                users_profile.id
--  6   bisafit_wearable_data            connection_id          bisafit_wearable_connections.id
--  7   bisafit_challenges               created_by             users_profile.id
--  8   bisafit_challenge_participants   challenge_id           bisafit_challenges.id
--  9   bisafit_challenge_participants   user_id                users_profile.id
--  10  bisafit_streaks                  user_id                users_profile.id
--  11  bisafit_user_badges              user_id                users_profile.id
--  12  bisafit_user_badges              badge_id               bisafit_badges.id
--  13  bisafit_xp_log                   user_id                users_profile.id
--  14  bisafit_subscriptions            user_id                users_profile.id
--  15  bisafit_subscriptions            plan_id                bisafit_subscription_plans.id
--  16  bisafit_food_log                 user_id                users_profile.id
--  17  bisafit_water_log                user_id                users_profile.id
--  18  bisafit_body_metrics             user_id                users_profile.id
--  19  bisafit_daily_summary            user_id                users_profile.id
--  20  bisafit_brand_voice              updated_by             users_profile.id
--  21  bisafit_audit_log                actor_id               users_profile.id
--  22  bisafit_notifications_queue      user_id                users_profile.id
--  23  bisafit_integrations             user_id                users_profile.id
--  24  bisafit_follows                  follower_id            users_profile.id
--  25  bisafit_follows                  following_id           users_profile.id
--  26  bisafit_workout_likes            user_id                users_profile.id
--  27  bisafit_activity_feed            actor_id               users_profile.id
--  28  bisafit_referrals                referrer_id            users_profile.id
--  29  bisafit_referrals                referee_id             users_profile.id
--  30  users_profile                    referred_by            users_profile.id
--  31  bisafit_coach_clients            assigned_plan_id       workout_plans.id (nullable)
--  32  bisafit_wearable_data            (cascade delete)       bisafit_wearable_connections.id
--  33  bisafit_challenge_participants   (cascade delete)       bisafit_challenges.id
--  34  bisafit_user_badges              (cascade delete)       bisafit_badges.id
--  35  bisafit_xp_log                   (restrict delete)      users_profile.id
--  36  bisafit_subscriptions            (restrict delete)      users_profile.id
--  37  bisafit_food_log                 (cascade delete)       users_profile.id
--  38  bisafit_activity_feed            (set null on delete)   users_profile.id
--
-- =============================================================================
-- SECTION 6 : INDEXES (187 indexes)
-- =============================================================================
--
--  Indexing strategy summary:
--
--  a) Primary Keys (26)
--     Every table carries a uuid DEFAULT gen_random_uuid() PK with a
--     btree index automatically created by PostgreSQL.
--
--  b) Foreign Key Indexes (38)
--     One btree index per FK column to prevent sequential scans on joins
--     and cascading operations.
--
--  c) User / Owner Lookup Indexes (22)
--     Composite (user_id, created_at DESC) on all per-user log / diary
--     tables to accelerate paginated timeline queries.
--
--  d) Date / Time Range Indexes (18)
--     (user_id, logged_date) on food_log; (user_id, measured_at) on
--     body_metrics; (user_id, summary_date) on daily_summary;
--     (recorded_at) on wearable_data; (start_date, end_date) on challenges.
--
--  e) Status / Enum Filter Indexes (14)
--     Partial indexes e.g. WHERE status = 'active' on subscriptions,
--     WHERE sent_at IS NULL on notifications_queue,
--     WHERE onboarding_completed = false on users_profile.
--
--  f) Unique Constraint Indexes (12)
--     bisafit_follows (follower_id, following_id);
--     bisafit_workout_likes (user_id, workout_id);
--     bisafit_streaks (user_id, streak_type);
--     bisafit_user_badges (user_id, badge_id);
--     bisafit_challenge_participants (challenge_id, user_id);
--     users_profile (referral_code);
--     bisafit_subscription_plans (stripe_price_id);
--     bisafit_wearable_connections (user_id, provider);
--     bisafit_daily_summary (user_id, summary_date);
--     bisafit_referrals (referrer_id, referee_id);
--     bisafit_integrations (user_id, provider);
--     bisafit_brand_voice (key).
--
--  g) Full-Text Search Indexes (8)
--     GIN indexes on tsvector columns for exercise_library (name, category,
--     muscle_groups), food_log (food_name, brand), challenges (title,
--     description), and activity_feed (metadata jsonb).
--
--  h) JSONB GIN Indexes (10)
--     GIN on raw_payload (wearable_data), config (integrations),
--     features (subscription_plans), permissions (roles),
--     metadata (activity_feed), old_data / new_data (audit_log),
--     data (notifications_queue), secondary_goals / available_equipment
--     (users_profile).
--
--  i) Covering / Composite Query Indexes (39)
--     Tailored to the most frequent application queries identified during
--     audit, e.g.:
--       (coach_id, status) on bisafit_coach_clients
--       (user_id, event_type, created_at) on bisafit_xp_log
--       (actor_id, event_type, created_at) on bisafit_activity_feed
--       (challenge_id, completed, rank) on bisafit_challenge_participants
--       (user_id, notification_type, sent_at) on notifications_queue
--       (referrer_id, reward_granted_at) on bisafit_referrals
--
--  TOTAL INDEXES : 187
--
-- =============================================================================
-- SECTION 7 : TRIGGERS (18 updated_at triggers)
-- =============================================================================
--
--  All triggers call bisafit_set_updated_at() BEFORE UPDATE FOR EACH ROW.
--
--  #   Trigger name                              Table
--  --  ----------------------------------------  -----------------------------
--  1   trg_users_profile_updated_at              users_profile
--  2   trg_exercise_library_updated_at           bisafit_exercise_library
--  3   trg_coach_clients_updated_at              bisafit_coach_clients
--  4   trg_messages_updated_at                   bisafit_messages
--  5   trg_wearable_connections_updated_at       bisafit_wearable_connections
--  6   trg_challenges_updated_at                 bisafit_challenges
--  7   trg_challenge_participants_updated_at     bisafit_challenge_participants
--  8   trg_streaks_updated_at                    bisafit_streaks
--  9   trg_badges_updated_at                     bisafit_badges
--  10  trg_subscriptions_updated_at              bisafit_subscriptions
--  11  trg_subscription_plans_updated_at         bisafit_subscription_plans
--  12  trg_food_log_updated_at                   bisafit_food_log
--  13  trg_body_metrics_updated_at               bisafit_body_metrics
--  14  trg_daily_summary_updated_at              bisafit_daily_summary
--  15  trg_brand_voice_updated_at                bisafit_brand_voice
--  16  trg_notifications_queue_updated_at        bisafit_notifications_queue
--  17  trg_integrations_updated_at               bisafit_integrations
--  18  trg_referrals_updated_at                  bisafit_referrals
--
-- =============================================================================
-- SECTION 8 : DEPLOYMENT NOTES & ROLLBACK GUIDANCE
-- =============================================================================
--
--  Deployment method : Supabase Management API (direct SQL execution)
--  Applied by        : BisaFit automated deployment pipeline
--  Idempotency       : All CREATE TABLE statements used IF NOT EXISTS;
--                      all ADD COLUMN statements guarded by existence checks;
--                      all CREATE POLICY statements used DROP POLICY IF EXISTS
--                      followed by CREATE POLICY to ensure clean state.
--
--  Rollback procedure:
--    1. Run the companion rollback script:
--       bisafit_audit_fix_round_001_ROLLBACK.sql
--    2. The rollback script drops all 26 new tables (CASCADE), removes
--       the 26 new columns from users_profile, drops the 21 functions,
--       and removes all associated indexes and triggers.
--    3. Estimated rollback time: < 2 minutes on current DB size.
--    4. WARNING: Rolling back will permanently delete all data written
--       to new tables after this migration was applied. Take a snapshot
--       before executing rollback in production.
--
--  Post-deployment validation checklist:
--    [ ] All 26 tables visible in Supabase Table Editor
--    [ ] RLS enabled on all 26 tables (check pg_tables + pg_policies)
--    [ ] users_profile column count delta = +26 vs pre-migration baseline
--    [ ] All 21 functions executable by service_role
--    [ ] 18 triggers appear in pg_trigger
--    [ ] 38 FK constraints appear in information_schema.referential_constraints
--    [ ] Index count on affected tables matches section 6 counts
--    [ ] bisafit_complete_onboarding() returns valid jsonb for test user
--    [ ] bisafit_admin_dashboard() returns valid jsonb
--    [ ] Stripe webhook handler functions exist and have correct search_path
--
-- =============================================================================
-- FULL SQL BODY NOTE
-- =============================================================================
--
-- The complete executable SQL (estimated ~4,800 lines) was applied directly
-- via the Supabase Management API during the audit fix deployment run.
-- It is stored separately as:
--
--   bisafit_audit_fix_round_001_FULL.sql
--
-- and is available in the private BisaFit engineering repository under:
--
--   /supabase/migrations/bisafit_audit_fix_round_001_FULL.sql
--
-- This documentation file (bisafit_audit_fix_round_001_DOCS.sql) serves as
-- the human-readable audit record and change management artefact for this
-- deployment round.
--
-- =============================================================================
-- END OF MIGRATION DOCUMENTATION FILE
-- Migration ID : bisafit_audit_fix_round_001
-- =============================================================================

SELECT 'bisafit_audit_fix_round_001 â documentation record loaded' AS migration_status;
