/**
 * BisaFit Landing Page
 * Marketing landing page with overview, features, pricing, and CTAs
 */

import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { 
  Dumbbell, 
  Utensils, 
  TrendingUp, 
  Sparkles, 
  Check, 
  ChevronDown,
  ChevronUp,
  Apple,
  Play,
  ArrowRight,
  Star,
  Zap,
  Calendar,
  Target,
  Heart,
  Shield,
  Clock,
  Users,
  Award,
  Loader2
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';

// Feature data
const FEATURES = [
  {
    icon: Sparkles,
    title: 'AI-Powered Workouts',
    description: 'Get personalized workout plans generated by AI that adapt to your goals, fitness level, and available equipment.',
  },
  {
    icon: Utensils,
    title: 'Smart Nutrition',
    description: 'Receive customized meal plans and nutrition guidance to fuel your workouts and maximize results.',
  },
  {
    icon: TrendingUp,
    title: 'Progress Tracking',
    description: 'Track your workouts, monitor progress, and see your transformation with detailed analytics.',
  },
  {
    icon: Calendar,
    title: 'Flexible Scheduling',
    description: 'Plan workouts around your life with smart scheduling that fits your busy lifestyle.',
  },
  {
    icon: Target,
    title: 'Goal-Focused Training',
    description: 'Whether building muscle, losing weight, or improving endurance — we create the perfect plan for YOU.',
  },
  {
    icon: Heart,
    title: 'Health Integration',
    description: 'Sync with Apple Health, Google Fit, Fitbit, and Strava to track all your health data in one place.',
  },
];

// How it works steps
const HOW_IT_WORKS = [
  {
    step: 1,
    title: 'Create Your Profile',
    description: 'Tell us about your fitness goals, experience level, and preferences.',
  },
  {
    step: 2,
    title: 'Get Your Plan',
    description: 'Our AI generates a personalized workout and nutrition plan just for you.',
  },
  {
    step: 3,
    title: 'Start Training',
    description: 'Follow your plan, track progress, and watch your transformation unfold.',
  },
];

// Pricing plans
const PRICING_PLANS = [
  {
    name: 'Monthly',
    price: '$14.99',
    period: '/month',
    description: 'Flexible month-to-month',
    features: [
      'AI-generated workout plans',
      'Personalized nutrition guidance',
      'Progress tracking & analytics',
      'Exercise demonstrations',
      'Health app integrations',
      'Cancel anytime',
    ],
    popular: false,
  },
  {
    name: 'Annual',
    price: '$11.24',
    period: '/month',
    billedAs: 'Billed annually at $134.91',
    description: '3 months FREE',
    features: [
      'Everything in Monthly',
      'Priority support',
      'Early access to new features',
      'Exclusive content',
      'Save $44.97 per year',
      '3 months FREE',
    ],
    popular: true,
    badge: '🎁 BEST VALUE',
  },
];

// FAQ data
const FAQS = [
  {
    question: 'How does the AI workout generation work?',
    answer: 'Our AI analyzes your fitness goals, current fitness level, available equipment, and schedule preferences to create a personalized workout plan. The plan adapts over time as you progress and provide feedback.',
  },
  {
    question: 'Can I use BisaFit without any equipment?',
    answer: 'Absolutely! BisaFit can generate effective bodyweight workout plans that require no equipment at all. Just let us know your equipment situation during onboarding.',
  },
  {
    question: 'How do I connect my fitness tracker?',
    answer: 'BisaFit integrates with Apple Health, Google Fit, Fitbit, and Strava. Simply go to Settings > Connected Apps and follow the prompts to connect your preferred platform.',
  },
  {
    question: 'Can I cancel my subscription anytime?',
    answer: 'Yes! You can cancel your subscription at any time. For monthly plans, you\'ll have access until the end of your billing period. Annual plans work the same way.',
  },
  {
    question: 'Is BisaFit suitable for beginners?',
    answer: 'Yes! BisaFit is designed for all fitness levels. Our AI creates appropriate workouts whether you\'re just starting out or you\'re an experienced athlete.',
  },
  {
    question: 'Do you offer a free trial?',
    answer: 'We offer a preview of the app before you subscribe. Once you\'re ready to unlock all features, you can choose the plan that works best for you.',
  },
];

// Testimonials (placeholder)
const TESTIMONIALS = [
  {
    name: 'Sarah M.',
    role: 'Lost 25 lbs',
    content: 'BisaFit completely changed my approach to fitness. The AI workouts are challenging but achievable, and I\'ve never felt better!',
    rating: 5,
  },
  {
    name: 'James K.',
    role: 'Gained muscle mass',
    content: 'As someone who struggled to stay consistent, BisaFit\'s personalized plans and progress tracking kept me motivated. Highly recommend!',
    rating: 5,
  },
  {
    name: 'Emily R.',
    role: 'Marathon runner',
    content: 'The integration with Strava is seamless. I love how BisaFit combines strength training with my running schedule.',
    rating: 5,
  },
];

export default function LandingPage() {
  const navigate = useNavigate();
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const handleGetStarted = () => {
    navigate('/auth');
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="sticky top-0 z-50 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center gap-2">
              <Dumbbell className="h-8 w-8 text-primary" />
              <span className="text-2xl font-bold">BisaFit</span>
            </div>
            
            <div className="hidden md:flex items-center gap-8">
              <a href="#features" className="text-muted-foreground hover:text-foreground transition-colors">Features</a>
              <a href="#how-it-works" className="text-muted-foreground hover:text-foreground transition-colors">How It Works</a>
              <a href="#pricing" className="text-muted-foreground hover:text-foreground transition-colors">Pricing</a>
              <a href="#faq" className="text-muted-foreground hover:text-foreground transition-colors">FAQ</a>
            </div>

            <div className="flex items-center gap-3">
              <Button variant="ghost" onClick={() => navigate('/auth')}>
                Sign In
              </Button>
              <Button onClick={handleGetStarted}>
                Get Started
              </Button>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-background to-primary/10" />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 md:py-32 relative">
          <div className="text-center max-w-4xl mx-auto">
            <Badge className="mb-6 px-4 py-1.5 text-sm" variant="secondary">
              🚀 AI-Powered Fitness Revolution
            </Badge>
            
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold tracking-tight mb-6">
              Your Personal
              <span className="text-primary"> AI Fitness</span>
              <br />Coach
            </h1>
            
            <p className="text-xl md:text-2xl text-muted-foreground mb-10 max-w-2xl mx-auto">
              Transform your body with personalized workout plans, smart nutrition guidance, and progress tracking — all powered by AI.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
              <Button size="lg" className="text-lg px-8 h-14" onClick={handleGetStarted}>
                Start Your Journey
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
              <Button size="lg" variant="outline" className="text-lg px-8 h-14" asChild>
                <a href="#features">
                  Learn More
                  <ChevronDown className="ml-2 h-5 w-5" />
                </a>
              </Button>
            </div>

            {/* App Store Buttons */}
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              <p className="text-sm text-muted-foreground">Coming soon to:</p>
              <div className="flex gap-3">
                <Button variant="outline" className="gap-2" disabled>
                  <Apple className="h-5 w-5" />
                  App Store
                </Button>
                <Button variant="outline" className="gap-2" disabled>
                  <Play className="h-5 w-5" />
                  Google Play
                </Button>
              </div>
            </div>

            {/* Trust badges */}
            <div className="mt-16 flex flex-wrap justify-center gap-8 items-center text-muted-foreground">
              <div className="flex items-center gap-2">
                <Shield className="h-5 w-5" />
                <span className="text-sm">Secure & Private</span>
              </div>
              <div className="flex items-center gap-2">
                <Users className="h-5 w-5" />
                <span className="text-sm">Join Thousands of Users</span>
              </div>
              <div className="flex items-center gap-2">
                <Award className="h-5 w-5" />
                <span className="text-sm">Expert-Backed Plans</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20 md:py-32 bg-muted/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge className="mb-4" variant="secondary">Features</Badge>
            <h2 className="text-3xl md:text-5xl font-bold mb-4">Everything You Need to Succeed</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              BisaFit combines cutting-edge AI with proven fitness science to help you achieve your goals.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {FEATURES.map((feature, index) => (
              <Card key={index} className="border-0 shadow-lg hover:shadow-xl transition-shadow">
                <CardContent className="p-8">
                  <div className="h-14 w-14 rounded-2xl bg-primary/10 flex items-center justify-center mb-6">
                    <feature.icon className="h-7 w-7 text-primary" />
                  </div>
                  <h3 className="text-xl font-semibold mb-3">{feature.title}</h3>
                  <p className="text-muted-foreground">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section id="how-it-works" className="py-20 md:py-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge className="mb-4" variant="secondary">How It Works</Badge>
            <h2 className="text-3xl md:text-5xl font-bold mb-4">Start in 3 Simple Steps</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Getting started with BisaFit is easy. Here's how it works.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 lg:gap-12">
            {HOW_IT_WORKS.map((item, index) => (
              <div key={index} className="text-center">
                <div className="h-20 w-20 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-3xl font-bold mx-auto mb-6">
                  {item.step}
                </div>
                <h3 className="text-xl font-semibold mb-3">{item.title}</h3>
                <p className="text-muted-foreground">{item.description}</p>
              </div>
            ))}
          </div>

          <div className="text-center mt-12">
            <Button size="lg" onClick={handleGetStarted}>
              Get Started Now
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 md:py-32 bg-muted/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge className="mb-4" variant="secondary">Testimonials</Badge>
            <h2 className="text-3xl md:text-5xl font-bold mb-4">Loved by Fitness Enthusiasts</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              See what our users are saying about their BisaFit journey.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {TESTIMONIALS.map((testimonial, index) => (
              <Card key={index} className="border-0 shadow-lg">
                <CardContent className="p-8">
                  <div className="flex gap-1 mb-4">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} className="h-5 w-5 fill-yellow-400 text-yellow-400" />
                    ))}
                  </div>
                  <p className="text-muted-foreground mb-6 italic">"{testimonial.content}"</p>
                  <div>
                    <p className="font-semibold">{testimonial.name}</p>
                    <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-20 md:py-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge className="mb-4" variant="secondary">Pricing</Badge>
            <h2 className="text-3xl md:text-5xl font-bold mb-4">Simple, Transparent Pricing</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Choose the plan that works best for you. Cancel anytime.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {PRICING_PLANS.map((plan, index) => (
              <Card 
                key={index} 
                className={cn(
                  "relative border-2 transition-all hover:shadow-xl",
                  plan.popular ? "border-primary shadow-lg scale-105" : "border-border"
                )}
              >
                {plan.badge && (
                  <div className="absolute -top-4 left-1/2 -translate-x-1/2">
                    <Badge className="px-4 py-1 text-sm bg-primary">{plan.badge}</Badge>
                  </div>
                )}
                <CardContent className="p-8">
                  <div className="text-center mb-8">
                    <h3 className="text-2xl font-bold mb-2">{plan.name}</h3>
                    <p className="text-muted-foreground mb-4">{plan.description}</p>
                    <div className="flex items-baseline justify-center gap-1">
                      <span className="text-5xl font-bold">{plan.price}</span>
                      <span className="text-muted-foreground">{plan.period}</span>
                    </div>
                    {plan.billedAs && (
                      <p className="text-sm text-muted-foreground mt-2">{plan.billedAs}</p>
                    )}
                  </div>

                  <ul className="space-y-4 mb-8">
                    {plan.features.map((feature, i) => (
                      <li key={i} className="flex items-center gap-3">
                        <Check className="h-5 w-5 text-primary flex-shrink-0" />
                        <span>{feature}</span>
                      </li>
                    ))}
                  </ul>

                  <Button 
                    className="w-full" 
                    size="lg"
                    variant={plan.popular ? "default" : "outline"}
                    onClick={handleGetStarted}
                  >
                    Get Started
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="py-20 md:py-32 bg-muted/30">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <Badge className="mb-4" variant="secondary">FAQ</Badge>
            <h2 className="text-3xl md:text-5xl font-bold mb-4">Frequently Asked Questions</h2>
            <p className="text-xl text-muted-foreground">
              Got questions? We've got answers.
            </p>
          </div>

          <div className="space-y-4">
            {FAQS.map((faq, index) => (
              <Card key={index} className="border-0 shadow-md">
                <button
                  className="w-full p-6 text-left flex justify-between items-center"
                  onClick={() => setOpenFaq(openFaq === index ? null : index)}
                >
                  <span className="font-semibold pr-4">{faq.question}</span>
                  {openFaq === index ? (
                    <ChevronUp className="h-5 w-5 flex-shrink-0 text-muted-foreground" />
                  ) : (
                    <ChevronDown className="h-5 w-5 flex-shrink-0 text-muted-foreground" />
                  )}
                </button>
                {openFaq === index && (
                  <div className="px-6 pb-6">
                    <p className="text-muted-foreground">{faq.answer}</p>
                  </div>
                )}
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 md:py-32 bg-primary text-primary-foreground">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-5xl font-bold mb-6">
            Ready to Transform Your Fitness?
          </h2>
          <p className="text-xl opacity-90 mb-10 max-w-2xl mx-auto">
            Join thousands of users who have already started their fitness journey with BisaFit. Your personalized plan is waiting.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              size="lg" 
              variant="secondary" 
              className="text-lg px-8 h-14"
              onClick={handleGetStarted}
            >
              Start Your Journey
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-background border-t py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-4 gap-12">
            {/* Brand */}
            <div className="md:col-span-2">
              <div className="flex items-center gap-2 mb-4">
                <Dumbbell className="h-8 w-8 text-primary" />
                <span className="text-2xl font-bold">BisaFit</span>
              </div>
              <p className="text-muted-foreground mb-6 max-w-md">
                Your personal AI fitness coach. Get personalized workout plans, nutrition guidance, and track your progress — all in one app.
              </p>
              <div className="flex gap-3">
                <Button variant="outline" size="sm" disabled>
                  <Apple className="h-4 w-4 mr-2" />
                  App Store
                </Button>
                <Button variant="outline" size="sm" disabled>
                  <Play className="h-4 w-4 mr-2" />
                  Google Play
                </Button>
              </div>
            </div>

            {/* Links */}
            <div>
              <h4 className="font-semibold mb-4">Product</h4>
              <ul className="space-y-3">
                <li><a href="#features" className="text-muted-foreground hover:text-foreground transition-colors">Features</a></li>
                <li><a href="#pricing" className="text-muted-foreground hover:text-foreground transition-colors">Pricing</a></li>
                <li><a href="#faq" className="text-muted-foreground hover:text-foreground transition-colors">FAQ</a></li>
                <li><Link to="/auth" className="text-muted-foreground hover:text-foreground transition-colors">Sign In</Link></li>
              </ul>
            </div>

            {/* Legal */}
            <div>
              <h4 className="font-semibold mb-4">Legal</h4>
              <ul className="space-y-3">
                <li><Link to="/terms" className="text-muted-foreground hover:text-foreground transition-colors">Terms of Service</Link></li>
                <li><Link to="/privacy" className="text-muted-foreground hover:text-foreground transition-colors">Privacy Policy</Link></li>
              </ul>

              <h4 className="font-semibold mb-4 mt-8">Contact</h4>
              <ul className="space-y-3">
                <li><a href="mailto:support@bisafit.com" className="text-muted-foreground hover:text-foreground transition-colors">support@bisafit.com</a></li>
              </ul>
            </div>
          </div>

          <div className="border-t mt-12 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="text-sm text-muted-foreground">
              © 2026 Bisa Group, LLC. All rights reserved.
            </p>
            <p className="text-sm text-muted-foreground">
              Made with ❤️ for fitness enthusiasts everywhere
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
